apiVersion: v1
kind: Service
metadata:
  name: maptiler
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: maptiler
  ports:
    - port: 8101
      targetPort: http
      protocol: TCP
      name: http
