apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-dev

metadata:
    labels:
        app.kubernetes.io/instance: dashboard-dev
        environment: development

commonAnnotations:
    description: "Dashboard (DEV)"

resources:
    - ../../base

images:
    -   name: registry.univ.leitwert.net/lagebild/t4-frontend/frontend
        newTag: latest

configMapGenerator:
    - name: dashboard
      behavior: merge
      literals:
          - NEXT_PUBLIC_FRONTEND_API_URL=https://dev-api.univ.leitwert.net/api
