apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: service.yaml
namespace: frontend-dev
images:
  - name: docker.io/lup7043/dashboard
    newTag: latest